
const Global = {
  PLAYING: 'PLAYING',
  STREAMING: 'STREAMING',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED',
  ERROR: 'ERROR',
  METADATA_UPDATED: 'METADATA_UPDATED',
  BUFFERING: 'BUFFERING',
  START_PREPARING: 'START_PREPARING', // Android only
  BUFFERING_START: 'BUFFERING_START', // Android only
};

export default Global;

